export const TTS_VOICE_OPTIONS = [
  { label: '晓晓（女声，中文）', value: 'zh-CN-XiaoxiaoNeural' },
  { label: '云希（男声，中文）', value: 'zh-CN-YunxiNeural' },
  { label: '晓伊（女声，中文）', value: 'zh-CN-XiaoyiNeural' },
  { label: '晓辰（女声，中文）', value: 'zh-CN-XiaochenNeural' },
  { label: '晓涵（女声，中文）', value: 'zh-CN-XiaohanNeural' },
  { label: '晓墨（女声，中文）', value: 'zh-CN-XiaomoNeural' },
  { label: '晓秋（女声，中文）', value: 'zh-CN-XiaoqiuNeural' },
  { label: '晓睿（女声，中文）', value: 'zh-CN-XiaoruiNeural' },
  { label: '晓双（女声，中文）', value: 'zh-CN-XiaoshuangNeural' },
  { label: '晓颜（女声，中文）', value: 'zh-CN-XiaoyanNeural' },
  { label: '晓悠（女声，中文）', value: 'zh-CN-XiaoyouNeural' },
  { label: '云健（男声，中文）', value: 'zh-CN-YunjianNeural' },
  { label: '云夏（男声，中文）', value: 'zh-CN-YunxiaNeural' },
  { label: '云扬（男声，中文）', value: 'zh-CN-YunyangNeural' },
  { label: '云泽（男声，中文）', value: 'zh-CN-YunzeNeural' },
  { label: 'Jenny（女声，英文）', value: 'en-US-JennyNeural' },
  { label: 'Guy（男声，英文）', value: 'en-US-GuyNeural' },
  { label: 'Aria（女声，英文）', value: 'en-US-AriaNeural' },
  { label: 'Ana（女声，英文）', value: 'en-US-AnaNeural' },
  { label: 'Ava（女声，英文）', value: 'en-US-AvaNeural' },
  { label: 'Emma（女声，英文）', value: 'en-US-EmmaNeural' },
  { label: 'Michelle（女声，英文）', value: 'en-US-MichelleNeural' },
  { label: 'Christopher（男声，英文）', value: 'en-US-ChristopherNeural' },
  { label: 'Brian（男声，英文）', value: 'en-US-BrianNeural' },
  { label: 'Davis（男声，英文）', value: 'en-US-DavisNeural' },
  { label: 'Eric（男声，英文）', value: 'en-US-EricNeural' },
  { label: 'Roger（男声，英文）', value: 'en-US-RogerNeural' },
] as const

